### ISSUE TITLE
Clarify License

### ISSUE THREAD

**Issue by jonwedell** [nbremer/occupationscanvas#3]
We really love this visualization and were hoping to adapt it for use on our [academic and non-commercial web site](http://www.bmrb.wisc.edu). This repository current doesn't have any license information. Are you okay with us using it, provided that we maintain attribution in the source?

Thanks,
Jon

**Comment by nbremer** [comment]
Thank you! I've now added a license.md file (MIT), which should work for you I think. But having some form of attribution would indeed be appreciated :)
